# Generated by Django 4.1.3 on 2022-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
