# Generated by Django 4.1.3 on 2022-11-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
